
FROM debian:latest
LABEL maintainer="lgf4591@outlook.com"
RUN mkdir -p /workspace
RUN  apt-get  update && export DEBIAN_FRONTEND=noninteractive     &&  apt-get  install -y  curl wget bash zsh fish tmux git 
RUN sh ../common_build.sh
