
FROM alpine:latest
LABEL maintainer="lgf4591@outlook.com"
RUN mkdir -p /workspace
RUN  apk  update && export DEBIAN_FRONTEND=noninteractive     &&  apk  add  curl wget bash zsh fish tmux git 
RUN sh build.sh
